[package]
name = "cached"
version = "0.13.1"
authors = ["James Kominick <james@kominick.com>"]
description = "Generic cache implementations and simplified function memoization"
repository = "https://github.com/jaemk/cached"
documentation = "https://docs.rs/cached"
readme = "README.md"
categories = ["caching"]
keywords = ["caching", "cache", "memoize", "lru"]
license = "MIT"
edition = "2018"

[badges]
travis-ci = { repository = "jaemk/cached", branch = "master" }

[features]
default = ["proc_macro"]
proc_macro = ["async-std", "cached_proc_macro"]

[dependencies]
once_cell = "1"

[dependencies.async-std]
version = "^1.5.0"
optional = true
features = ["attributes"]

[dependencies.cached_proc_macro]
version = "0.1.1"
path = "cached_proc_macro"
optional = true

[dev-dependencies]
tokio = { version = "0.2.21", features = ["macros", "time"] }

[workspace]
members = ["cached_proc_macro"]
